-- CreateEnum
CREATE TYPE "JobStatus" AS ENUM ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED');

-- CreateEnum
CREATE TYPE "JobStage" AS ENUM ('INITIALIZED', 'DETECTING_LANGUAGE', 'GENERATING_STORY', 'CREATING_STORY', 'CREATING_MAIN_CHARS', 'CREATING_SEC_CHARS', 'CREATING_FIRST_SCENE', 'GENERATING_ITEMS', 'GENERATING_BANNER', 'UPLOADING_BANNER', 'GENERATING_SCENE_IMG', 'UPLOADING_SCENE_IMG', 'FINALIZING');

-- AlterTable
ALTER TABLE "user" ADD COLUMN     "credits" INTEGER NOT NULL DEFAULT 5,
ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- CreateTable
CREATE TABLE "job" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "status" "JobStatus" NOT NULL DEFAULT 'PENDING',
    "stage" "JobStage" NOT NULL DEFAULT 'INITIALIZED',
    "error" TEXT,
    "input" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "job_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "job" ADD CONSTRAINT "job_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;
