export const genreIds: string[] = [
  "fantasy-medieval",
  "post-apocalyptic",
  "space-opera",
  "cyberpunk",
  "steampunk",
  "horror",
  "mystery",
  "adventure",
  "action",
  "romance",
  "historical",
  "super-heroes",
  "urban-fantasy",
  "western",
  "mythology",
  "slice-of-life",
  "dark-fantasy",
  "dystopian",
  "paranormal",
  "time-travel",
  "fantasy",
  "sci-fi",
  "thriller",
  "comedy",
  "drama",
  "family",
  "sports",
  "music",
  "food",
  "travel",
  "pets",
  "supernatural"
] as const;

export type Genre = typeof genreIds[number];